version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony-app
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    networks:
      - monitoring

  nginx:
    image: nginx:latest
    container_name: symfony-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - monitoring

  database:
    image: mysql:8.0
    container_name: symfony-db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - monitoring

volumes:
  db_data:

networks:
  monitoring:
    external: false
