version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9099:9090"  # Host:Container
   volumes:
  - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3033:3000"
    networks:
      - monitoring

networks:
  monitoring:
