global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'symfony'
    static_configs:
      - targets: ['172.17.0.1:8000']  # <- IP de ta machine Debian
        labels:
          service: symfony

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: prometheus
