global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'symfony'
    static_configs:
      - targets: ['symfony-app:8000']
        labels:
          service: symfony

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: prometheus
